### ISSUE TITLE
Homepage structure should mimic "Current Issue"

### ISSUE THREAD

**Issue by chrismlusk** [UIllLRev/lawreview2016-theme#5]
Currently, homepage displays in chronological order. Brad would prefer this to be structured like "Current Issue" page, with articles before student notes.

**Comment by chrismlusk** [comment]
@bradleywilliams24, I think there needs to be more discussion about this first.

Basically, what is the purpose and difference of the homepage vs. Current Issue? The Current Issue page is obvious; it's the current issue. But if the homepage is structured the same way, then what value does that add to the site?

It seems to me that the homepage would be more of a living representation of Illinois Law Review — here's our most recent, best, topical, etc. content that we think you should explore. That's why the four homepage areas communicate a distinct visual hierarchy. If you turn the homepage into Current Issue 2.0, your two most prominent areas are filled with content that rarely changes (five times a year?) and quickly becomes stale. Not to mention that approach diminishes all online and blog pieces, which hurts your efforts to build a robust digital presence.

Of course, I realize I'm looking at this as someone who thinks about news and media websites — which I admit are different beasts. So maybe the right answer is to scrap this sort of homepage and just have the current issue be the primary page. (I'm skeptical this is the solution, though.)

But these are just the thoughts of an outsider! Let me know what you and others think.

**Comment by bradleywilliams24** [comment]
@chrismlusk I mostly agree with you. I also am not married to this idea either. I like your visual hierarchy. As much as I like the idea of the homepage being a living representation of the journal (and would like to use this in the future), I believe others care more about the prestige of the professors publishing with us and strengths of the articles themselves. 

In a perfect world, all of our content—print articles, online articles, blog posts, and symposium submissions—would be content that we would like to highlight as relevant and important. Realistically, our print articles are our strongest pieces. We are still trying to strengthen the quality of our online content. Not that I would not stand behind any piece we have on ILR Online, but it is clear to me that others are not willing to give student-written or practitioner-written posts the time of day they deserve.

Would a better solution be to only highlight print articles and professor-written articles? For the time being, can we only highlight certain articles with a specific tag and set the homepage to only show these pieces?

**Comment by chrismlusk** [comment]
@bradleywilliams24, that all makes sense. What is ideal and what is realistic won't always line up, but I think we can figure out good ways to address this in the next phase. For now, I'll modify the homepage filter for only articles and symposium pieces.
