### ISSUE TITLE
Improve display of online rankings

### ISSUE THREAD

**Issue by chrismlusk** [UIllLRev/lawreview2016-theme#8]
The table is squished and is hard to read.

**Comment by chrismlusk** [comment]
@mloar, the easiest fix for now is to update the page itself (via wp-admin). I've edited the [Online Rankings page on the dev site](https://dev.illinoislawreview.org/online-rankings/), so if that looks good to you then I'd just copy and paste the page contents from the dev to live site.

**Comment by mloar** [comment]
Oh yeah, that looks a lot better.

**Comment by chrismlusk** [comment]
@mloar I've updated the live page, but the changes made in #10 need to be pushed to the site before the table fits properly.

**Comment by mloar** [comment]
I've pushed the changes to the live site.
