### ISSUE TITLE
Add a "First 100 Days" page

### ISSUE THREAD

**Issue by chrismlusk** [UIllLRev/lawreview2016-theme#9]
We need to add a section/page to showcase the upcoming symposium.

**Comment by chrismlusk** [comment]
@bradleywilliams24, my understanding is this will be designed as a semi-standalone piece of the site. The landing page would introduce the symposium and highlight key content, and then link off to the detail pages for each piece. What, if any, other components were you thinking of including?

**Comment by bradleywilliams24** [comment]
@chrismlusk Where in the navigation will this be placed? Should we create a new secondary tab for it as "President Trump's First 100 Days Symposium"? I believe we are also going to have video of each of the speakers from the event—how would you like to incorporate this with the rest of the content?

I ask you this because, after talking with Lindsey, it seemed like both of you had a very specific vision for this section.

**Comment by chrismlusk** [comment]
@bradleywilliams24, Lindsey and I talked through her ideas last night. I'll put together some sketches or mockups this week and share them. As for the navigation questions, my suggestion is to use the hero block (full-width row up top) on the homepage to promote this and then add a new nav link later.

For the videos, so will there be one video file for each of the seven (I think that's what Lindsey said?) speakers? And these speakers are also submitting a written piece that will be showcased on the site, right? If yes, will their pieces and their speeches cover the same topic? If yes, then without knowing the design specifics yet, I imagine the videos could be incorporated into the articles.

Some of this will make better sense once we have a wireframe to build off of. I'll be working on ILR later this week.

**Comment by bradleywilliams24** [comment]
@chrismlusk Sounds good. I was not clear—I agree that adding it to the hero block is the best solution. 

I do not know if the Professor coordinating the event decided exactly how we will use the footage. I will follow up with him now. 

Yes, the piece and the speech should cover the same topic (barring some movement from Trump's administration after the speech on the the topic they presented on). 

Thanks for all of your work on this!
